### ISSUE TITLE
Hotspot activity not displaying any record

### ISSUE THREAD

**Issue by 9Jbl9** [jamiew/helium-discord-bot#25]
Hi, I have added your bot to my server and was testing, but could not see any activity. kindly see the attached file for the same. Please let me know if I am doing something wrong.
![Screen Shot 2021-09-01 at 12 54 47 pm](https://user-images.githubusercontent.com/85490839/131629774-8a81d938-f40d-4a1b-99e6-4eb203b5e523.jpg)

**Comment by jamiew** [comment]
Looks like something broke, I can't get any activity results at all right now! Taking a look. Thanks for reporting the bug
